version: '3'

services:
  db:
    container_name: db
    image: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
    - database:/var/lib/mysql

  backend:
    container_name: 'ccg_backend'
    image: univnantes/ccg_backend
    environment:
      WAIT_HOSTS: mysql:3306
    restart: on-failure
    ports:
    - "8080:8080"
    depends_on:
      - db

volumes:
  database: {}