spring:
  datasource:
    initialization-mode: always
    data: classpath:data.sql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/database?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080
  servlet:
    contextPath: /api
  error:
    include-message: always
    include-binding-errors: always